name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/cloud-connector-template.yml'
      - 'CloudConnectorTemplate/**'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Pack with dotnet
      run: dotnet pack cloud-connector-template.csproj --configuration Release 

    - name: Push to Nuget
      run: dotnet nuget push **/bin/Release/*.nupkg -s https://www.nuget.org/ -k ${{ secrets.NUGET_KEY }} --skip-duplicate 