name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/windows-service-template-dnf.yml'
      - 'windows-service-framework-template.csproj'
      - 'WindowsServiceFramework/**'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
   
    - name: Pack with dotnet
      run: dotnet pack windows-service-framework-template.csproj --configuration Release 

    - name: Push to Nuget
      run: dotnet nuget push **/bin/Release/Blue10.Templates.Windows.Service.DNF.*.nupkg -s https://www.nuget.org/ -k ${{ secrets.NUGET_KEY }} --skip-duplicate 